//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabasisNommer
    {
        public string Exam { get; set; }
        public string VraestelKode { get; set; }
        public string Msheet_Laaste_Syfer { get; set; }
        public Nullable<int> PuntestaatlMaksimumPunt { get; set; }
        public Nullable<int> Nasionaal { get; set; }
        public Nullable<double> GetalKandidate { get; set; }
        public Nullable<double> GetalKandidate_A { get; set; }
        public Nullable<int> GetalKandidate_B { get; set; }
        public Nullable<int> DB_No { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
