//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDate
    {
        public string Description { get; set; }
        public string ExamDate1 { get; set; }
        public bool ExamClaimPerHour { get; set; }
        public Nullable<System.DateTime> DateLastChanged { get; set; }
        public string ChangedBy { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
