//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITOR_SERVERS
    {
        public int Server_ID { get; set; }
        public string Server_Name { get; set; }
        public string IP_Address { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> LastCheck { get; set; }
        public Nullable<System.DateTime> LastSuccess { get; set; }
        public Nullable<int> DisplaySequence { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
    }
}
