//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITOR_SERVERS_DETAIL
    {
        public int Server_ID { get; set; }
        public Nullable<int> SQLServer_CPU_Utilization { get; set; }
        public Nullable<int> System_Idle_Process { get; set; }
        public Nullable<int> Other_Process_CPU_Utilization { get; set; }
        public Nullable<System.DateTime> Event_Time { get; set; }
    }
}
