//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNTA
    {
        public string MsType { get; set; }
        public Nullable<int> MsSeries { get; set; }
        public Nullable<int> MsTests { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RegType { get; set; }
        public string SubjCode { get; set; }
        public Nullable<int> SubjNo { get; set; }
        public Nullable<int> Paper { get; set; }
        public Nullable<int> CeNo { get; set; }
        public Nullable<int> Cands { get; set; }
        public Nullable<int> SegNo { get; set; }
        public string ExamNo { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> PaperMark { get; set; }
        public string Race { get; set; }
        public string Language { get; set; }
        public string Gender { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
