//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punte
    {
        public Nullable<int> Sentrum { get; set; }
        public string Marksheet { get; set; }
        public string ExamNo { get; set; }
        public Nullable<double> Vr1 { get; set; }
        public Nullable<double> Vr2 { get; set; }
        public Nullable<double> Vr3 { get; set; }
        public Nullable<double> Tot { get; set; }
        public Nullable<double> F7 { get; set; }
        public Nullable<int> Hash { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
