//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraagOntledingPerWKODPerVraestel
    {
        public string Eksamen { get; set; }
        public string VrstelKode { get; set; }
        public Nullable<short> GetalVraeOpVraestel { get; set; }
        public Nullable<int> VraestelMaksimum { get; set; }
        public Nullable<double> GemidVr1 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_1 { get; set; }
        public Nullable<double> GemidVr2 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_2 { get; set; }
        public Nullable<double> GemidVr3 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_3 { get; set; }
        public Nullable<double> GemidVr4 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_4 { get; set; }
        public Nullable<double> GemidVr5 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_5 { get; set; }
        public Nullable<double> GemidVr6 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_6 { get; set; }
        public Nullable<double> GemidVr7 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_7 { get; set; }
        public Nullable<double> GemidVr8 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_8 { get; set; }
        public Nullable<double> GemidVr9 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_9 { get; set; }
        public Nullable<double> GemidVr10 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_10 { get; set; }
        public Nullable<double> GemidVr11 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_11 { get; set; }
        public Nullable<double> GemidVr12 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_12 { get; set; }
        public Nullable<double> GemidVr13 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_13 { get; set; }
        public Nullable<double> GemidVr14 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_14 { get; set; }
        public Nullable<double> GemidVr15 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_15 { get; set; }
        public Nullable<double> GemidVr16 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_16 { get; set; }
        public Nullable<double> GemidVr17 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_17 { get; set; }
        public Nullable<double> GemidVr18 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_18 { get; set; }
        public Nullable<double> GemidVr19 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_19 { get; set; }
        public Nullable<double> GemidVr20 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_20 { get; set; }
        public Nullable<double> GemidVr21 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_21 { get; set; }
        public Nullable<double> GemidVr22 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_22 { get; set; }
        public Nullable<double> GemidVr23 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_23 { get; set; }
        public Nullable<double> GemidVr24 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_24 { get; set; }
        public Nullable<double> GemidVr25 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_25 { get; set; }
        public Nullable<double> GemidVr26 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_26 { get; set; }
        public Nullable<double> GemidVr27 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_27 { get; set; }
        public Nullable<double> GemidVr28 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_28 { get; set; }
        public Nullable<double> GemidVr29 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_29 { get; set; }
        public Nullable<double> GemidVr30 { get; set; }
        public Nullable<double> CountOfPS_VRAAG_30 { get; set; }
        public Nullable<double> GemidVraestel { get; set; }
        public Nullable<int> CountOfPS_VRAESTELPUNT { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
