//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraagOntledingPerSentrumPerVraestel_Relatief
    {
        public string Eksamen { get; set; }
        public string Sort { get; set; }
        public Nullable<int> EMDC_No { get; set; }
        public string Distrik { get; set; }
        public Nullable<int> PS_EKS_SM_NO { get; set; }
        public string SentrumNm { get; set; }
        public string Vak { get; set; }
        public string Graad { get; set; }
        public string Vakkode { get; set; }
        public string VrstelKode { get; set; }
        public string Vaknaam { get; set; }
        public Nullable<short> GetalVraeOpVraestel { get; set; }
        public Nullable<double> RelVr1 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_1 { get; set; }
        public Nullable<double> RelVr2 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_2 { get; set; }
        public Nullable<double> RelVr3 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_3 { get; set; }
        public Nullable<double> RelVr4 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_4 { get; set; }
        public Nullable<double> RelVr5 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_5 { get; set; }
        public Nullable<double> RelVr6 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_6 { get; set; }
        public Nullable<double> RelVr7 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_7 { get; set; }
        public Nullable<double> RelVr8 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_8 { get; set; }
        public Nullable<double> RelVr9 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_9 { get; set; }
        public Nullable<double> RelVr10 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_10 { get; set; }
        public Nullable<double> RelVr11 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_11 { get; set; }
        public Nullable<double> RelVr12 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_12 { get; set; }
        public Nullable<double> RelVr13 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_13 { get; set; }
        public Nullable<double> RelVr14 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_14 { get; set; }
        public Nullable<double> RelVr15 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_15 { get; set; }
        public Nullable<double> RelVr16 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_16 { get; set; }
        public Nullable<double> RelVr17 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_17 { get; set; }
        public Nullable<double> RelVr18 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_18 { get; set; }
        public Nullable<double> RelVr19 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_19 { get; set; }
        public Nullable<double> RelVr20 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_20 { get; set; }
        public Nullable<double> RelVr21 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_21 { get; set; }
        public Nullable<double> RelVr22 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_22 { get; set; }
        public Nullable<double> RelVr23 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_23 { get; set; }
        public Nullable<double> RelVr24 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_24 { get; set; }
        public Nullable<double> RelVr25 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_25 { get; set; }
        public Nullable<double> RelVr26 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_26 { get; set; }
        public Nullable<double> RelVr27 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_27 { get; set; }
        public Nullable<double> RelVr28 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_28 { get; set; }
        public Nullable<double> RelVr29 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_29 { get; set; }
        public Nullable<double> RelVr30 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_30 { get; set; }
        public Nullable<double> RelVraestel { get; set; }
        public Nullable<int> CountOfPS_VRAESTELPUNT { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
