//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraagOntledingPerSentrumEnVraestel_OBO
    {
        public Nullable<double> EMDC_No { get; set; }
        public string Vakkode { get; set; }
        public Nullable<short> VraestelNommer { get; set; }
        public string VraestelKode { get; set; }
        public string VraestelK { get; set; }
        public string VrstNaam { get; set; }
        public Nullable<double> GetalKandidate { get; set; }
        public Nullable<int> VraestelMaksimumPunt { get; set; }
        public Nullable<short> GetalVrae { get; set; }
        public Nullable<short> GetalVraeOpVraestel { get; set; }
        public Nullable<float> VraagMaks1 { get; set; }
        public Nullable<float> VraagMaks2 { get; set; }
        public Nullable<float> VraagMaks3 { get; set; }
        public Nullable<float> VraagMaks4 { get; set; }
        public Nullable<float> VraagMaks5 { get; set; }
        public Nullable<float> VraagMaks6 { get; set; }
        public Nullable<float> VraagMaks7 { get; set; }
        public Nullable<float> VraagMaks8 { get; set; }
        public Nullable<float> VraagMaks9 { get; set; }
        public Nullable<float> VraagMaks10 { get; set; }
        public Nullable<float> VraagMaks11 { get; set; }
        public Nullable<float> VraagMaks12 { get; set; }
        public Nullable<float> VraagMaks13 { get; set; }
        public Nullable<float> VraagMaks14 { get; set; }
        public Nullable<float> VraagMaks15 { get; set; }
        public Nullable<float> VraagMaks16 { get; set; }
        public Nullable<float> VraagMaks17 { get; set; }
        public Nullable<float> VraagMaks18 { get; set; }
        public Nullable<float> VraagMaks19 { get; set; }
        public Nullable<float> VraagMaks20 { get; set; }
        public Nullable<float> VraagMaks21 { get; set; }
        public Nullable<float> VraagMaks22 { get; set; }
        public Nullable<float> VraagMaks23 { get; set; }
        public Nullable<float> VraagMaks24 { get; set; }
        public Nullable<float> VraagMaks25 { get; set; }
        public Nullable<float> VraagMaks26 { get; set; }
        public Nullable<float> VraagMaks27 { get; set; }
        public Nullable<float> VraagMaks28 { get; set; }
        public Nullable<float> VraagMaks29 { get; set; }
        public Nullable<float> VraagMaks30 { get; set; }
        public Nullable<short> GetalKombinasiesVanKeuseVrae { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo1 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo1 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae1 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo2 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo2 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae2 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo3 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo3 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae3 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo4 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo4 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae4 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo5 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo5 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae5 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo6 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo6 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae6 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
