//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vraagleer2020
    {
        public string Eksamen { get; set; }
        public string Vakkode { get; set; }
        public Nullable<double> VraestelNommer { get; set; }
        public string VrstelKode { get; set; }
        public string VraestelKode { get; set; }
        public Nullable<double> DatabasisNommer { get; set; }
        public Nullable<double> GetalKandidateSubstelsel_A { get; set; }
        public Nullable<double> GetalKandidateSubstelsel_B { get; set; }
        public Nullable<double> GetalVraeOpVraestel { get; set; }
        public Nullable<double> MaksVraeBeantwoord { get; set; }
        public Nullable<double> VraestelMaksimum { get; set; }
        public Nullable<double> PuntestaatlMaksimum { get; set; }
        public string VraagNaam1 { get; set; }
        public Nullable<double> VraagMaks1 { get; set; }
        public bool TelVirVraestelMaks1 { get; set; }
        public string VraagNaam2 { get; set; }
        public Nullable<double> VraagMaks2 { get; set; }
        public bool TelVirVraestelMaks2 { get; set; }
        public string VraagNaam3 { get; set; }
        public Nullable<double> VraagMaks3 { get; set; }
        public bool TelVirVraestelMaks3 { get; set; }
        public string VraagNaam4 { get; set; }
        public Nullable<double> VraagMaks4 { get; set; }
        public bool TelVirVraestelMaks4 { get; set; }
        public string VraagNaam5 { get; set; }
        public Nullable<double> VraagMaks5 { get; set; }
        public bool TelVirVraestelMaks5 { get; set; }
        public string VraagNaam6 { get; set; }
        public Nullable<double> VraagMaks6 { get; set; }
        public bool TelVirVraestelMaks6 { get; set; }
        public string VraagNaam7 { get; set; }
        public Nullable<double> VraagMaks7 { get; set; }
        public bool TelVirVraestelMaks7 { get; set; }
        public string VraagNaam8 { get; set; }
        public Nullable<double> VraagMaks8 { get; set; }
        public bool TelVirVraestelMaks8 { get; set; }
        public string VraagNaam9 { get; set; }
        public Nullable<double> VraagMaks9 { get; set; }
        public bool TelVirVraestelMaks9 { get; set; }
        public string VraagNaam10 { get; set; }
        public Nullable<double> VraagMaks10 { get; set; }
        public bool TelVirVraestelMaks10 { get; set; }
        public string VraagNaam11 { get; set; }
        public Nullable<double> VraagMaks11 { get; set; }
        public bool TelVirVraestelMaks11 { get; set; }
        public string VraagNaam12 { get; set; }
        public Nullable<double> VraagMaks12 { get; set; }
        public bool TelVirVraestelMaks12 { get; set; }
        public string VraagNaam13 { get; set; }
        public Nullable<double> VraagMaks13 { get; set; }
        public bool TelVirVraestelMaks13 { get; set; }
        public string VraagNaam14 { get; set; }
        public Nullable<double> VraagMaks14 { get; set; }
        public bool TelVirVraestelMaks14 { get; set; }
        public string VraagNaam15 { get; set; }
        public Nullable<double> VraagMaks15 { get; set; }
        public bool TelVirVraestelMaks15 { get; set; }
        public string VraagNaam16 { get; set; }
        public Nullable<double> VraagMaks16 { get; set; }
        public bool TelVirVraestelMaks16 { get; set; }
        public string VraagNaam17 { get; set; }
        public Nullable<double> VraagMaks17 { get; set; }
        public bool TelVirVraestelMaks17 { get; set; }
        public string VraagNaam18 { get; set; }
        public string VraagMaks18 { get; set; }
        public bool TelVirVraestelMaks18 { get; set; }
        public string VraagNaam19 { get; set; }
        public string VraagMaks19 { get; set; }
        public bool TelVirVraestelMaks19 { get; set; }
        public string VraagNaam20 { get; set; }
        public string VraagMaks20 { get; set; }
        public bool TelVirVraestelMaks20 { get; set; }
        public string VraagNaam21 { get; set; }
        public string VraagMaks21 { get; set; }
        public bool TelVirVraestelMaks21 { get; set; }
        public string VraagNaam22 { get; set; }
        public string VraagMaks22 { get; set; }
        public bool TelVirVraestelMaks22 { get; set; }
        public string VraagNaam23 { get; set; }
        public string VraagMaks23 { get; set; }
        public bool TelVirVraestelMaks23 { get; set; }
        public string VraagNaam24 { get; set; }
        public string VraagMaks24 { get; set; }
        public bool TelVirVraestelMaks24 { get; set; }
        public string VraagNaam25 { get; set; }
        public string VraagMaks25 { get; set; }
        public bool TelVirVraestelMaks25 { get; set; }
        public string VraagNaam26 { get; set; }
        public string VraagMaks26 { get; set; }
        public bool TelVirVraestelMaks26 { get; set; }
        public string VraagNaam27 { get; set; }
        public string VraagMaks27 { get; set; }
        public bool TelVirVraestelMaks27 { get; set; }
        public string VraagNaam28 { get; set; }
        public string VraagMaks28 { get; set; }
        public bool TelVirVraestelMaks28 { get; set; }
        public string VraagNaam29 { get; set; }
        public string VraagMaks29 { get; set; }
        public bool TelVirVraestelMaks29 { get; set; }
        public string VraagNaam30 { get; set; }
        public string VraagMaks30 { get; set; }
        public bool TelVirVraestelMaks30 { get; set; }
        public Nullable<double> GetalKombinasiesVanKeuseVrae { get; set; }
        public Nullable<double> GetalKombinasiesTeBeantwoord { get; set; }
        public Nullable<double> KeuseVraeEersteVrgNo1 { get; set; }
        public Nullable<double> KeuseVraeLaasteVrgNo1 { get; set; }
        public Nullable<double> KeuseVraeGetalVrae1 { get; set; }
        public Nullable<double> KeuseVraeEersteVrgNo2 { get; set; }
        public Nullable<double> KeuseVraeLaasteVrgNo2 { get; set; }
        public Nullable<double> KeuseVraeGetalVrae2 { get; set; }
        public Nullable<double> KeuseVraeEersteVrgNo3 { get; set; }
        public Nullable<double> KeuseVraeLaasteVrgNo3 { get; set; }
        public Nullable<double> KeuseVraeGetalVrae3 { get; set; }
        public string KeuseVraeEersteVrgNo4 { get; set; }
        public string KeuseVraeLaasteVrgNo4 { get; set; }
        public string KeuseVraeGetalVrae4 { get; set; }
        public string KeuseVraeEersteVrgNo5 { get; set; }
        public string KeuseVraeLaasteVrgNo5 { get; set; }
        public string KeuseVraeGetalVrae5 { get; set; }
        public string KeuseVraeEersteVrgNo6 { get; set; }
        public string KeuseVraeLaasteVrgNo6 { get; set; }
        public string KeuseVraeGetalVrae6 { get; set; }
        public Nullable<double> GetalAfdelingsGeheelKeuses { get; set; }
        public string GetalAfdelingsTeBeantwoord { get; set; }
        public string AfdelingEersteVrgNo1 { get; set; }
        public string AfdelingLaasteVrgNo1 { get; set; }
        public string AfdelingEersteVrgNo2 { get; set; }
        public string AfdelingLaasteVrgNo2 { get; set; }
        public string AfdelingEersteVrgNo3 { get; set; }
        public string AfdelingLaasteVrgNo3 { get; set; }
        public string AfdelingEersteVrgNo4 { get; set; }
        public string AfdelingLaasteVrgNo4 { get; set; }
        public string AfdelingEersteVrgNo5 { get; set; }
        public string AfdelingLaasteVrgNo5 { get; set; }
        public string AfdelingEersteVrgNo6 { get; set; }
        public string AfdelingLaasteVrgNo6 { get; set; }
        public bool WPM { get; set; }
        public string WPM_Min { get; set; }
        public string WPM_Max { get; set; }
        public Nullable<double> Foutvlag { get; set; }
    }
}
