//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCapturing
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraestelLokaleKleur
    {
        public int ID_Gebou { get; set; }
        public string Gebou { get; set; }
        public string Kleur { get; set; }
        public string Supervisor { get; set; }
        public string ScriptCoordinator { get; set; }
        public string DataCaptureSupervisor { get; set; }
        public string ScriptsRoomnumber { get; set; }
        public string DataCaptureRoomnumber { get; set; }
        public Nullable<int> Eetsaal { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
