//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmalSaam_Data
    {
        public Nullable<int> PS_EKS_DAT { get; set; }
        public string PS_KODE { get; set; }
        public string PS_VRAESTELKODE { get; set; }
        public string VraestelK { get; set; }
        public Nullable<int> PS_EKS_SM_NO { get; set; }
        public string PS_ID_NO { get; set; }
        public Nullable<float> PS_VRAAG_1 { get; set; }
        public Nullable<float> PS_VRAAG_2 { get; set; }
        public Nullable<float> PS_VRAAG_3 { get; set; }
        public Nullable<float> PS_VRAAG_4 { get; set; }
        public Nullable<float> PS_VRAAG_5 { get; set; }
        public Nullable<float> PS_VRAAG_6 { get; set; }
        public Nullable<float> PS_VRAAG_7 { get; set; }
        public Nullable<float> PS_VRAAG_8 { get; set; }
        public Nullable<float> PS_VRAAG_9 { get; set; }
        public Nullable<float> PS_VRAAG_10 { get; set; }
        public Nullable<float> PS_VRAAG_11 { get; set; }
        public Nullable<float> PS_VRAAG_12 { get; set; }
        public Nullable<float> PS_VRAAG_13 { get; set; }
        public Nullable<float> PS_VRAAG_14 { get; set; }
        public Nullable<float> PS_VRAAG_15 { get; set; }
        public Nullable<float> PS_VRAAG_16 { get; set; }
        public Nullable<float> PS_VRAAG_17 { get; set; }
        public Nullable<float> PS_VRAAG_18 { get; set; }
        public Nullable<float> PS_VRAAG_19 { get; set; }
        public Nullable<float> PS_VRAAG_20 { get; set; }
        public Nullable<float> PS_VRAAG_21 { get; set; }
        public Nullable<float> PS_VRAAG_22 { get; set; }
        public Nullable<float> PS_VRAAG_23 { get; set; }
        public Nullable<float> PS_VRAAG_24 { get; set; }
        public Nullable<float> PS_VRAAG_25 { get; set; }
        public Nullable<float> PS_VRAAG_26 { get; set; }
        public Nullable<float> PS_VRAAG_27 { get; set; }
        public Nullable<float> PS_VRAAG_28 { get; set; }
        public Nullable<float> PS_VRAAG_29 { get; set; }
        public Nullable<float> PS_VRAAG_30 { get; set; }
        public Nullable<float> PS_VRAESTELPUNT { get; set; }
        public Nullable<float> PS_GEKONTROLEERDEPUNT { get; set; }
        public Nullable<bool> PS_PuntGekontroleer { get; set; }
        public Nullable<int> PS_WPM { get; set; }
        public Nullable<bool> PS_Hoofraam_888 { get; set; }
        public string PS_Msheet { get; set; }
        public Nullable<byte> PS_MarksheetSort { get; set; }
        public string PS_Cand { get; set; }
        public string PS_Ras { get; set; }
        public string PS_Taal { get; set; }
        public string PS_Geslag { get; set; }
        public Nullable<float> PS_KAFTOTAAL { get; set; }
        public Nullable<short> PS_BOX_NO { get; set; }
        public Nullable<byte> PS_FOUT_VLAG { get; set; }
        public Nullable<byte> Hoofraam_Leerno { get; set; }
        public Nullable<int> Rekenaarno { get; set; }
        public string PS_ChangedBy { get; set; }
        public string PS_DateLastChanged { get; set; }
        public Nullable<int> PS_Punt_Na_Vraesteltabel { get; set; }
        public Nullable<int> PS_Kand_Getrek_vir_Mod { get; set; }
        public string PS_GekontroleerDeur { get; set; }
        public string PS_DatumGekontroleer { get; set; }
        public string AuditTrail { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
