//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCapturer
    {
        public string KampusEng { get; set; }
        public string ID { get; set; }
        public string ID_Number { get; set; }
        public string SURNAME { get; set; }
        public string Initials { get; set; }
        public string Name { get; set; }
        public string BeskrywingEng { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
