//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBE_Stats
    {
        public string System { get; set; }
        public string Exam { get; set; }
        public int Sub { get; set; }
        public int Prov { get; set; }
        public string Province { get; set; }
        public string Subj { get; set; }
        public string Paper { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Outstanding { get; set; }
        public Nullable<int> Captured { get; set; }
        public Nullable<double> PercCaptured { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<double> PercAbsent { get; set; }
        public Nullable<int> Verified { get; set; }
        public Nullable<double> PercVerified { get; set; }
        public Nullable<double> PercDone { get; set; }
    }
}
