//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKS_VraagPunte_A_ZULHL10
    {
        public Nullable<int> PS_EKS_DAT { get; set; }
        public string PS_KODE { get; set; }
        public string PS_VRAESTELKODE { get; set; }
        public Nullable<int> PS_EKS_SM_NO { get; set; }
        public string PS_ID_NO { get; set; }
        public Nullable<float> PS_VRAAG_1 { get; set; }
        public Nullable<float> PS_VRAAG_2 { get; set; }
        public Nullable<float> PS_VRAAG_3 { get; set; }
        public Nullable<float> PS_VRAAG_4 { get; set; }
        public Nullable<float> PS_VRAAG_5 { get; set; }
        public Nullable<float> PS_VRAAG_6 { get; set; }
        public Nullable<float> PS_VRAESTELPUNT { get; set; }
        public Nullable<float> PS_GEKONTROLEERDEPUNT { get; set; }
        public Nullable<bool> PS_PuntGekontroleer { get; set; }
        public Nullable<bool> PS_Hoofraam_888 { get; set; }
        public string PS_Msheet { get; set; }
        public byte PS_MarksheetSort { get; set; }
        public Nullable<short> PS_Cand { get; set; }
        public string PS_Ras { get; set; }
        public string PS_Taal { get; set; }
        public string PS_Geslag { get; set; }
        public Nullable<float> PS_KAFTOTAAL { get; set; }
        public Nullable<short> PS_BOX_NO { get; set; }
        public Nullable<byte> PS_FOUT_VLAG { get; set; }
        public string PS_ChangedBy { get; set; }
        public string PS_DateLastChanged { get; set; }
        public string PS_GekontroleerDeur { get; set; }
        public string PS_DatumGekontroleer { get; set; }
        public Nullable<double> Hash { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
