//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKS_PUNTESTATE
    {
        public string PS_EKS_DAT { get; set; }
        public string PS_KODE { get; set; }
        public string PS_VAKKODE { get; set; }
        public short PS_VRSTEL_NO { get; set; }
        public int PS_EKS_SM_NO { get; set; }
        public string PS_ID_NO { get; set; }
        public short PS_VRSTEL_PUNT { get; set; }
        public Nullable<short> PS_PuntestaatlMaksimumPunt { get; set; }
        public Nullable<bool> PS_Hoofraam_888 { get; set; }
        public string PS_Msheet { get; set; }
        public string Msheet_Laaste_Syfer { get; set; }
        public Nullable<int> PS_MarksheetSort { get; set; }
        public string PS_Cand { get; set; }
        public string PS_Ras { get; set; }
        public string PS_Taal { get; set; }
        public string PS_Geslag { get; set; }
        public string NUUT { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
        public string MSheet9 { get; set; }
    }
}
