//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NSC_VraagpunteStelselEntities : DbContext
    {
        public NSC_VraagpunteStelselEntities()
            : base("name=NSC_VraagpunteStelselEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EKS_VraagPunte_A_ACCN10> EKS_VraagPunte_A_ACCN10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ACCN20> EKS_VraagPunte_A_ACCN20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ACCNZ10> EKS_VraagPunte_A_ACCNZ10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRFA10> EKS_VraagPunte_A_AFRFA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRFA20> EKS_VraagPunte_A_AFRFA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRFA30> EKS_VraagPunte_A_AFRFA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRHL10> EKS_VraagPunte_A_AFRHL10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRHL20> EKS_VraagPunte_A_AFRHL20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRHL30> EKS_VraagPunte_A_AFRHL30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRSA10> EKS_VraagPunte_A_AFRSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRSA20> EKS_VraagPunte_A_AFRSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AFRSA30> EKS_VraagPunte_A_AFRSA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AGRM10> EKS_VraagPunte_A_AGRM10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AGRS10> EKS_VraagPunte_A_AGRS10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AGRS20> EKS_VraagPunte_A_AGRS20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_AGRT10> EKS_VraagPunte_A_AGRT10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ARBSA10> EKS_VraagPunte_A_ARBSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ARBSA20> EKS_VraagPunte_A_ARBSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_BSTD10> EKS_VraagPunte_A_BSTD10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_BSTD20> EKS_VraagPunte_A_BSTD20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_BSTDZ10> EKS_VraagPunte_A_BSTDZ10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_CATN10> EKS_VraagPunte_A_CATN10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_CATN20> EKS_VraagPunte_A_CATN20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_CHNSA10> EKS_VraagPunte_A_CHNSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_CNST10> EKS_VraagPunte_A_CNST10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_CVTC10> EKS_VraagPunte_A_CVTC10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_CVTV10> EKS_VraagPunte_A_CVTV10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_CVTW10> EKS_VraagPunte_A_CVTW10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_DNCE10> EKS_VraagPunte_A_DNCE10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_DRMA10> EKS_VraagPunte_A_DRMA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_DSGN10> EKS_VraagPunte_A_DSGN10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ECON10> EKS_VraagPunte_A_ECON10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ECON20> EKS_VraagPunte_A_ECON20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ELTD10> EKS_VraagPunte_A_ELTD10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ELTE10> EKS_VraagPunte_A_ELTE10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ELTP10> EKS_VraagPunte_A_ELTP10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGFA10> EKS_VraagPunte_A_ENGFA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGFA20> EKS_VraagPunte_A_ENGFA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGFA30> EKS_VraagPunte_A_ENGFA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGHL10> EKS_VraagPunte_A_ENGHL10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGHL20> EKS_VraagPunte_A_ENGHL20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGHL30> EKS_VraagPunte_A_ENGHL30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGSA10> EKS_VraagPunte_A_ENGSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGSA20> EKS_VraagPunte_A_ENGSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ENGSA30> EKS_VraagPunte_A_ENGSA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_EQNS10> EKS_VraagPunte_A_EQNS10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_FRHSA10> EKS_VraagPunte_A_FRHSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_FRHSA20> EKS_VraagPunte_A_FRHSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_GEOG10> EKS_VraagPunte_A_GEOG10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_GEOG20> EKS_VraagPunte_A_GEOG20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_GRDS10> EKS_VraagPunte_A_GRDS10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_GRDS20> EKS_VraagPunte_A_GRDS20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_GRMSA10> EKS_VraagPunte_A_GRMSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_GRMSA20> EKS_VraagPunte_A_GRMSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_HBRSA10> EKS_VraagPunte_A_HBRSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_HBRSA20> EKS_VraagPunte_A_HBRSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_HIST10> EKS_VraagPunte_A_HIST10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_HIST20> EKS_VraagPunte_A_HIST20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_HOSP10> EKS_VraagPunte_A_HOSP10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_INFT10> EKS_VraagPunte_A_INFT10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_INFT20> EKS_VraagPunte_A_INFT20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_LFSC10> EKS_VraagPunte_A_LFSC10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_LFSC20> EKS_VraagPunte_A_LFSC20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MANSA10> EKS_VraagPunte_A_MANSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MANSA20> EKS_VraagPunte_A_MANSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MATH10> EKS_VraagPunte_A_MATH10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MATH20> EKS_VraagPunte_A_MATH20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MCTA10> EKS_VraagPunte_A_MCTA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MCTF10> EKS_VraagPunte_A_MCTF10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MCTW10> EKS_VraagPunte_A_MCTW10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MLIT10> EKS_VraagPunte_A_MLIT10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MLIT20> EKS_VraagPunte_A_MLIT20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MRSC10> EKS_VraagPunte_A_MRSC10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MRSC20> EKS_VraagPunte_A_MRSC20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MRTE10> EKS_VraagPunte_A_MRTE10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MUSC10> EKS_VraagPunte_A_MUSC10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_MUSC20> EKS_VraagPunte_A_MUSC20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_NTSC10> EKS_VraagPunte_A_NTSC10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_NTSC20> EKS_VraagPunte_A_NTSC20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_PHSC10> EKS_VraagPunte_A_PHSC10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_PHSC20> EKS_VraagPunte_A_PHSC20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_PRGFA10> EKS_VraagPunte_A_PRGFA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_PRGFA20> EKS_VraagPunte_A_PRGFA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_PRGFA30> EKS_VraagPunte_A_PRGFA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_PRGSA10> EKS_VraagPunte_A_PRGSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_PRGSA20> EKS_VraagPunte_A_PRGSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_RLGS10> EKS_VraagPunte_A_RLGS10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_RLGS20> EKS_VraagPunte_A_RLGS20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_RLGSZ10> EKS_VraagPunte_A_RLGSZ10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_RLGSZ20> EKS_VraagPunte_A_RLGSZ20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SASHL10> EKS_VraagPunte_A_SASHL10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SASHL20> EKS_VraagPunte_A_SASHL20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SASHL30> EKS_VraagPunte_A_SASHL30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SESHL10> EKS_VraagPunte_A_SESHL10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SESHL20> EKS_VraagPunte_A_SESHL20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SESHL30> EKS_VraagPunte_A_SESHL30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SPES10> EKS_VraagPunte_A_SPES10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SPNSA10> EKS_VraagPunte_A_SPNSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_SPNSA20> EKS_VraagPunte_A_SPNSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_TMAT10> EKS_VraagPunte_A_TMAT10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_TMAT20> EKS_VraagPunte_A_TMAT20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_TRNP710> EKS_VraagPunte_A_TRNP710 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_TRSM10> EKS_VraagPunte_A_TRSM10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_TSCE10> EKS_VraagPunte_A_TSCE10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_TSCE20> EKS_VraagPunte_A_TSCE20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_URDFA10> EKS_VraagPunte_A_URDFA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_URDFA20> EKS_VraagPunte_A_URDFA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_URDFA30> EKS_VraagPunte_A_URDFA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_URDSA10> EKS_VraagPunte_A_URDSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_URDSA20> EKS_VraagPunte_A_URDSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_VSLA10> EKS_VraagPunte_A_VSLA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOFA10> EKS_VraagPunte_A_XHOFA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOFA20> EKS_VraagPunte_A_XHOFA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOFA30> EKS_VraagPunte_A_XHOFA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOHL10> EKS_VraagPunte_A_XHOHL10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOHL20> EKS_VraagPunte_A_XHOHL20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOHL30> EKS_VraagPunte_A_XHOHL30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOSA10> EKS_VraagPunte_A_XHOSA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOSA20> EKS_VraagPunte_A_XHOSA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_XHOSA30> EKS_VraagPunte_A_XHOSA30 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ZULHL10> EKS_VraagPunte_A_ZULHL10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ZULHL20> EKS_VraagPunte_A_ZULHL20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ZULHL30> EKS_VraagPunte_A_ZULHL30 { get; set; }
        public virtual DbSet<Puntestate> Puntestates { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vakke> Vakkes { get; set; }
        public virtual DbSet<Vraagleer> Vraagleers { get; set; }
        public virtual DbSet<Vraestelle> Vraestelles { get; set; }
        public virtual DbSet<Roles1> Roles1 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ZULFA10> EKS_VraagPunte_A_ZULFA10 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ZULFA20> EKS_VraagPunte_A_ZULFA20 { get; set; }
        public virtual DbSet<EKS_VraagPunte_A_ZULFA30> EKS_VraagPunte_A_ZULFA30 { get; set; }
        public virtual DbSet<ExamDate> ExamDates { get; set; }
        public virtual DbSet<GetalKandidatePerVraestel> GetalKandidatePerVraestels { get; set; }
        public virtual DbSet<EKS_PUNTESTATE> EKS_PUNTESTATE { get; set; }
        public virtual DbSet<PasswordResetRequest> PasswordResetRequests { get; set; }
        public virtual DbSet<DBE_Stats> DBE_Stats { get; set; }
        public virtual DbSet<vw_AllMarksheets> vw_AllMarksheets { get; set; }
        public virtual DbSet<vw_Marksheets_ACCN10> vw_Marksheets_ACCN10 { get; set; }
        public virtual DbSet<vw_Marksheets_ACCN20> vw_Marksheets_ACCN20 { get; set; }
        public virtual DbSet<vw_Marksheets_ACCNZ10> vw_Marksheets_ACCNZ10 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRFA10> vw_Marksheets_AFRFA10 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRFA20> vw_Marksheets_AFRFA20 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRFA30> vw_Marksheets_AFRFA30 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRHL10> vw_Marksheets_AFRHL10 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRHL20> vw_Marksheets_AFRHL20 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRHL30> vw_Marksheets_AFRHL30 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRSA10> vw_Marksheets_AFRSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRSA20> vw_Marksheets_AFRSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_AFRSA30> vw_Marksheets_AFRSA30 { get; set; }
        public virtual DbSet<vw_Marksheets_AGRM10> vw_Marksheets_AGRM10 { get; set; }
        public virtual DbSet<vw_Marksheets_AGRS10> vw_Marksheets_AGRS10 { get; set; }
        public virtual DbSet<vw_Marksheets_AGRS20> vw_Marksheets_AGRS20 { get; set; }
        public virtual DbSet<vw_Marksheets_AGRT10> vw_Marksheets_AGRT10 { get; set; }
        public virtual DbSet<vw_Marksheets_ARBSA10> vw_Marksheets_ARBSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_ARBSA20> vw_Marksheets_ARBSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_BSTD10> vw_Marksheets_BSTD10 { get; set; }
        public virtual DbSet<vw_Marksheets_BSTD20> vw_Marksheets_BSTD20 { get; set; }
        public virtual DbSet<vw_Marksheets_BSTDZ10> vw_Marksheets_BSTDZ10 { get; set; }
        public virtual DbSet<vw_Marksheets_CATN10> vw_Marksheets_CATN10 { get; set; }
        public virtual DbSet<vw_Marksheets_CATN20> vw_Marksheets_CATN20 { get; set; }
        public virtual DbSet<vw_Marksheets_CHNSA10> vw_Marksheets_CHNSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_CNST10> vw_Marksheets_CNST10 { get; set; }
        public virtual DbSet<vw_Marksheets_CVTC10> vw_Marksheets_CVTC10 { get; set; }
        public virtual DbSet<vw_Marksheets_CVTV10> vw_Marksheets_CVTV10 { get; set; }
        public virtual DbSet<vw_Marksheets_CVTW10> vw_Marksheets_CVTW10 { get; set; }
        public virtual DbSet<vw_Marksheets_DNCE10> vw_Marksheets_DNCE10 { get; set; }
        public virtual DbSet<vw_Marksheets_DRMA10> vw_Marksheets_DRMA10 { get; set; }
        public virtual DbSet<vw_Marksheets_DSGN10> vw_Marksheets_DSGN10 { get; set; }
        public virtual DbSet<vw_Marksheets_ECON10> vw_Marksheets_ECON10 { get; set; }
        public virtual DbSet<vw_Marksheets_ECON20> vw_Marksheets_ECON20 { get; set; }
        public virtual DbSet<vw_Marksheets_ELTD10> vw_Marksheets_ELTD10 { get; set; }
        public virtual DbSet<vw_Marksheets_ELTE10> vw_Marksheets_ELTE10 { get; set; }
        public virtual DbSet<vw_Marksheets_ELTP10> vw_Marksheets_ELTP10 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGFA10> vw_Marksheets_ENGFA10 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGFA20> vw_Marksheets_ENGFA20 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGFA30> vw_Marksheets_ENGFA30 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGHL10> vw_Marksheets_ENGHL10 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGHL20> vw_Marksheets_ENGHL20 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGHL30> vw_Marksheets_ENGHL30 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGSA10> vw_Marksheets_ENGSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGSA20> vw_Marksheets_ENGSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_ENGSA30> vw_Marksheets_ENGSA30 { get; set; }
        public virtual DbSet<vw_Marksheets_EQNS10> vw_Marksheets_EQNS10 { get; set; }
        public virtual DbSet<vw_Marksheets_FRHSA10> vw_Marksheets_FRHSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_FRHSA20> vw_Marksheets_FRHSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_GEOG10> vw_Marksheets_GEOG10 { get; set; }
        public virtual DbSet<vw_Marksheets_GEOG20> vw_Marksheets_GEOG20 { get; set; }
        public virtual DbSet<vw_Marksheets_GRDS10> vw_Marksheets_GRDS10 { get; set; }
        public virtual DbSet<vw_Marksheets_GRDS20> vw_Marksheets_GRDS20 { get; set; }
        public virtual DbSet<vw_Marksheets_GRMSA10> vw_Marksheets_GRMSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_GRMSA20> vw_Marksheets_GRMSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_HBRSA10> vw_Marksheets_HBRSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_HBRSA20> vw_Marksheets_HBRSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_HIST10> vw_Marksheets_HIST10 { get; set; }
        public virtual DbSet<vw_Marksheets_HIST20> vw_Marksheets_HIST20 { get; set; }
        public virtual DbSet<vw_Marksheets_HOSP10> vw_Marksheets_HOSP10 { get; set; }
        public virtual DbSet<vw_Marksheets_INFT10> vw_Marksheets_INFT10 { get; set; }
        public virtual DbSet<vw_Marksheets_INFT20> vw_Marksheets_INFT20 { get; set; }
        public virtual DbSet<vw_Marksheets_LFSC10> vw_Marksheets_LFSC10 { get; set; }
        public virtual DbSet<vw_Marksheets_LFSC20> vw_Marksheets_LFSC20 { get; set; }
        public virtual DbSet<vw_Marksheets_MANSA10> vw_Marksheets_MANSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_MANSA20> vw_Marksheets_MANSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_MATH10> vw_Marksheets_MATH10 { get; set; }
        public virtual DbSet<vw_Marksheets_MATH20> vw_Marksheets_MATH20 { get; set; }
        public virtual DbSet<vw_Marksheets_MCTA10> vw_Marksheets_MCTA10 { get; set; }
        public virtual DbSet<vw_Marksheets_MCTF10> vw_Marksheets_MCTF10 { get; set; }
        public virtual DbSet<vw_Marksheets_MCTW10> vw_Marksheets_MCTW10 { get; set; }
        public virtual DbSet<vw_Marksheets_MLIT10> vw_Marksheets_MLIT10 { get; set; }
        public virtual DbSet<vw_Marksheets_MLIT20> vw_Marksheets_MLIT20 { get; set; }
        public virtual DbSet<vw_Marksheets_MRSC10> vw_Marksheets_MRSC10 { get; set; }
        public virtual DbSet<vw_Marksheets_MRSC20> vw_Marksheets_MRSC20 { get; set; }
        public virtual DbSet<vw_Marksheets_MRTE10> vw_Marksheets_MRTE10 { get; set; }
        public virtual DbSet<vw_Marksheets_MUSC10> vw_Marksheets_MUSC10 { get; set; }
        public virtual DbSet<vw_Marksheets_MUSC20> vw_Marksheets_MUSC20 { get; set; }
        public virtual DbSet<vw_Marksheets_NTSC10> vw_Marksheets_NTSC10 { get; set; }
        public virtual DbSet<vw_Marksheets_NTSC20> vw_Marksheets_NTSC20 { get; set; }
        public virtual DbSet<vw_Marksheets_PHSC10> vw_Marksheets_PHSC10 { get; set; }
        public virtual DbSet<vw_Marksheets_PHSC20> vw_Marksheets_PHSC20 { get; set; }
        public virtual DbSet<vw_Marksheets_PRGFA10> vw_Marksheets_PRGFA10 { get; set; }
        public virtual DbSet<vw_Marksheets_PRGFA20> vw_Marksheets_PRGFA20 { get; set; }
        public virtual DbSet<vw_Marksheets_PRGFA30> vw_Marksheets_PRGFA30 { get; set; }
        public virtual DbSet<vw_Marksheets_PRGSA10> vw_Marksheets_PRGSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_PRGSA20> vw_Marksheets_PRGSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_RLGS10> vw_Marksheets_RLGS10 { get; set; }
        public virtual DbSet<vw_Marksheets_RLGS20> vw_Marksheets_RLGS20 { get; set; }
        public virtual DbSet<vw_Marksheets_RLGSZ10> vw_Marksheets_RLGSZ10 { get; set; }
        public virtual DbSet<vw_Marksheets_RLGSZ20> vw_Marksheets_RLGSZ20 { get; set; }
        public virtual DbSet<vw_Marksheets_SASHL10> vw_Marksheets_SASHL10 { get; set; }
        public virtual DbSet<vw_Marksheets_SASHL20> vw_Marksheets_SASHL20 { get; set; }
        public virtual DbSet<vw_Marksheets_SASHL30> vw_Marksheets_SASHL30 { get; set; }
        public virtual DbSet<vw_Marksheets_SESHL10> vw_Marksheets_SESHL10 { get; set; }
        public virtual DbSet<vw_Marksheets_SESHL20> vw_Marksheets_SESHL20 { get; set; }
        public virtual DbSet<vw_Marksheets_SESHL30> vw_Marksheets_SESHL30 { get; set; }
        public virtual DbSet<vw_Marksheets_SPES10> vw_Marksheets_SPES10 { get; set; }
        public virtual DbSet<vw_Marksheets_SPNSA10> vw_Marksheets_SPNSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_SPNSA20> vw_Marksheets_SPNSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_TMAT10> vw_Marksheets_TMAT10 { get; set; }
        public virtual DbSet<vw_Marksheets_TMAT20> vw_Marksheets_TMAT20 { get; set; }
        public virtual DbSet<vw_Marksheets_TRNP710> vw_Marksheets_TRNP710 { get; set; }
        public virtual DbSet<vw_Marksheets_TRSM10> vw_Marksheets_TRSM10 { get; set; }
        public virtual DbSet<vw_Marksheets_TSCE10> vw_Marksheets_TSCE10 { get; set; }
        public virtual DbSet<vw_Marksheets_TSCE20> vw_Marksheets_TSCE20 { get; set; }
        public virtual DbSet<vw_Marksheets_URDFA10> vw_Marksheets_URDFA10 { get; set; }
        public virtual DbSet<vw_Marksheets_URDFA20> vw_Marksheets_URDFA20 { get; set; }
        public virtual DbSet<vw_Marksheets_URDFA30> vw_Marksheets_URDFA30 { get; set; }
        public virtual DbSet<vw_Marksheets_URDSA10> vw_Marksheets_URDSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_URDSA20> vw_Marksheets_URDSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_VSLA10> vw_Marksheets_VSLA10 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOFA10> vw_Marksheets_XHOFA10 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOFA20> vw_Marksheets_XHOFA20 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOFA30> vw_Marksheets_XHOFA30 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOHL10> vw_Marksheets_XHOHL10 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOHL20> vw_Marksheets_XHOHL20 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOHL30> vw_Marksheets_XHOHL30 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOSA10> vw_Marksheets_XHOSA10 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOSA20> vw_Marksheets_XHOSA20 { get; set; }
        public virtual DbSet<vw_Marksheets_XHOSA30> vw_Marksheets_XHOSA30 { get; set; }
        public virtual DbSet<vw_Marksheets_ZULFA10> vw_Marksheets_ZULFA10 { get; set; }
        public virtual DbSet<vw_Marksheets_ZULFA20> vw_Marksheets_ZULFA20 { get; set; }
        public virtual DbSet<vw_Marksheets_ZULFA30> vw_Marksheets_ZULFA30 { get; set; }
        public virtual DbSet<vw_Marksheets_ZULHL10> vw_Marksheets_ZULHL10 { get; set; }
        public virtual DbSet<vw_Marksheets_ZULHL20> vw_Marksheets_ZULHL20 { get; set; }
        public virtual DbSet<vw_Marksheets_ZULHL30> vw_Marksheets_ZULHL30 { get; set; }
    
        public virtual int ApplyBusinessRules()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApplyBusinessRules");
        }
    
        public virtual int ApplyQueryRegister()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApplyQueryRegister");
        }
    
        public virtual int MONITOR_CED_CEI_EXM01()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_CED_CEI_EXM01");
        }
    
        public virtual int MONITOR_WCEDSQL01()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WCEDSQL01");
        }
    
        public virtual int MONITOR_WSPB00X4KP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4KP");
        }
    
        public virtual int MONITOR_WSPB00X4KS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4KS");
        }
    
        public virtual int MONITOR_WSPB00X4KW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4KW");
        }
    
        public virtual int MONITOR_WSPB00X4KX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4KX");
        }
    
        public virtual int MONITOR_WSPB00X4L5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4L5");
        }
    
        public virtual int MONITOR_WSPB00X4L9()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4L9");
        }
    
        public virtual int MONITOR_WSPB00X4LC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4LC");
        }
    
        public virtual int MONITOR_WSPB00X4LD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MONITOR_WSPB00X4LD");
        }
    
        public virtual int SearchAllTables(string searchStr)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchAllTables", searchStrParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_loaddata(string serverName, string campus)
        {
            var serverNameParameter = serverName != null ?
                new ObjectParameter("serverName", serverName) :
                new ObjectParameter("serverName", typeof(string));
    
            var campusParameter = campus != null ?
                new ObjectParameter("Campus", campus) :
                new ObjectParameter("Campus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_loaddata", serverNameParameter, campusParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Update_Subject_Status()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Subject_Status");
        }
    
        public virtual int UpdateCapturedBy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCapturedBy");
        }
    }
}
