//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetalKandidatePerVraestel
    {
        public string Eksamen { get; set; }
        public string PS_VAKKODE { get; set; }
        public Nullable<short> PS_VRSTEL_NO { get; set; }
        public Nullable<double> GetalKandidateSubstelsel_A { get; set; }
        public Nullable<double> GetalKandidateSubstelsel_B { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
