//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade12File
    {
        public string Msheet { get; set; }
        public string Examnr { get; set; }
        public string VakVrstel { get; set; }
        public string Subnr { get; set; }
        public Nullable<int> Paper { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<int> Cand { get; set; }
        public Nullable<int> Status1 { get; set; }
        public Nullable<int> Status2 { get; set; }
        public Nullable<int> centnr { get; set; }
        public Nullable<int> OLDCENTNR { get; set; }
        public string USER { get; set; }
        public string DATE { get; set; }
        public string Surname { get; set; }
        public Nullable<int> RegType { get; set; }
        public string Repeater { get; set; }
        public Nullable<int> SEQNR { get; set; }
        public string Methodcaptured { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
