//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntestate
    {
        public int Eksamen { get; set; }
        public string VoltydsPrivaat { get; set; }
        public string Puntestaat { get; set; }
        public string Puntestaat_Laaste_Syfer { get; set; }
        public string VraestelKode { get; set; }
        public Nullable<int> PuntestaatlMaksimumPunt { get; set; }
        public int Sentrum { get; set; }
        public Nullable<int> GetalKand { get; set; }
        public Nullable<int> GetalSkrifte { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<int> Box_Number { get; set; }
        public string ChangedBy { get; set; }
        public string DateLastChanged { get; set; }
        public string VerifiedBy { get; set; }
        public string DateVerified { get; set; }
        public string BoxedBy { get; set; }
        public string DateBoxed { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<int> Box_Original { get; set; }
        public string MSheet9 { get; set; }
        public string MSheet8 { get; set; }
    }
}
