//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sentrumadresly
    {
        public Nullable<int> DISTR { get; set; }
        public Nullable<int> CE_NO { get; set; }
        public string SCHOOL { get; set; }
        public Nullable<double> EMDC_No { get; set; }
        public Nullable<int> SentrumNo__oue { get; set; }
        public int SentrumNo { get; set; }
        public string EMIS { get; set; }
        public string SentrumNm { get; set; }
        public string SentrumNaam { get; set; }
        public string DiePrinsipaal { get; set; }
        public string Straatadres1 { get; set; }
        public string Straatadres2 { get; set; }
        public string Straatadres3 { get; set; }
        public string Straatposkode { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public Nullable<int> CourierRoeteNo { get; set; }
        public string UserNameUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> Druk { get; set; }
        public string Beheer { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> SmartLocking { get; set; }
        public Nullable<int> Kring { get; set; }
        public string ind { get; set; }
        public Nullable<bool> NonSll { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
