//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentrumsGetalPerVak
    {
        public string S_EKS_DAT { get; set; }
        public string S_VAKKODE { get; set; }
        public Nullable<int> S_EKS_SM_NO { get; set; }
        public Nullable<double> S_GetalKandidateSubstelsel_A { get; set; }
        public Nullable<double> S_GetalKandidateSubstelsel_B { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
