//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats_VerifiersReport
    {
        public Nullable<int> PS_EKS_DAT { get; set; }
        public string Verifier { get; set; }
        public string Date_Verified { get; set; }
        public Nullable<short> PC_Number { get; set; }
        public Nullable<double> Getal { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
