//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp
    {
        public string USer { get; set; }
        public string Timestamp { get; set; }
        public string Message { get; set; }
        public string Marksheet { get; set; }
        public string ExamNumber { get; set; }
        public string HashTotal { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
