//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public short Level { get; set; }
        public Nullable<System.DateTime> DateLastChanged { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<short> PC_Number { get; set; }
        public string Role { get; set; }
        public string ID_Number { get; set; }
        public string Campus { get; set; }
        public Nullable<decimal> CampusID { get; set; }
        public Nullable<decimal> AccessCardID { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
        public bool IsPasswordResetRequested { get; set; }
        public bool IsPasswordReset { get; set; }
        public string ResetToken { get; set; }
        public Nullable<System.DateTime> ResetTokenExpiry { get; set; }
    }
}
