//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vakke
    {
        public Nullable<bool> ValidTable { get; set; }
        public string Vakkode { get; set; }
        public string Subject { get; set; }
        public string Vak { get; set; }
        public Nullable<bool> PraktiesJaNee { get; set; }
        public string Body { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
