//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraagOntledingPerSentrumPerVraestel
    {
        public string Eksamen { get; set; }
        public Nullable<double> EMDC_No { get; set; }
        public string PS_KODE { get; set; }
        public Nullable<int> PS_EKS_SM_NO { get; set; }
        public string SentrumNm { get; set; }
        public string Vak { get; set; }
        public string Graad { get; set; }
        public string VrstelKode { get; set; }
        public string Vaknaam { get; set; }
        public Nullable<short> GetalVraeOpVraestel { get; set; }
        public Nullable<int> VraestelMaksimum { get; set; }
        public Nullable<double> GemVr1 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_1 { get; set; }
        public Nullable<double> GemVr2 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_2 { get; set; }
        public Nullable<double> GemVr3 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_3 { get; set; }
        public Nullable<double> GemVr4 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_4 { get; set; }
        public Nullable<double> GemVr5 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_5 { get; set; }
        public Nullable<double> GemVr6 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_6 { get; set; }
        public Nullable<double> GemVr7 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_7 { get; set; }
        public Nullable<double> GemVr8 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_8 { get; set; }
        public Nullable<double> GemVr9 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_9 { get; set; }
        public Nullable<double> GemVr10 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_10 { get; set; }
        public Nullable<double> GemVr11 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_11 { get; set; }
        public Nullable<double> GemVr12 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_12 { get; set; }
        public Nullable<double> GemVr13 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_13 { get; set; }
        public Nullable<double> GemVr14 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_14 { get; set; }
        public Nullable<double> GemVr15 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_15 { get; set; }
        public Nullable<double> GemVr16 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_16 { get; set; }
        public Nullable<double> GemVr17 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_17 { get; set; }
        public Nullable<double> GemVr18 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_18 { get; set; }
        public Nullable<double> GemVr19 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_19 { get; set; }
        public Nullable<double> GemVr20 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_20 { get; set; }
        public Nullable<double> GemVr21 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_21 { get; set; }
        public Nullable<double> GemVr22 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_22 { get; set; }
        public Nullable<double> GemVr23 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_23 { get; set; }
        public Nullable<double> GemVr24 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_24 { get; set; }
        public Nullable<double> GemVr25 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_25 { get; set; }
        public Nullable<double> GemVr26 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_26 { get; set; }
        public Nullable<double> GemVr27 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_27 { get; set; }
        public Nullable<double> GemVr28 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_28 { get; set; }
        public Nullable<double> GemVr29 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_29 { get; set; }
        public Nullable<double> GemVr30 { get; set; }
        public Nullable<int> CountOfPS_VRAAG_30 { get; set; }
        public Nullable<double> GemVraestel { get; set; }
        public Nullable<int> CountOfPS_VRAESTELPUNT { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
