//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraagleerPreviousYear
    {
        public string Eksamen { get; set; }
        public string Vakkode { get; set; }
        public short VraestelNommer { get; set; }
        public string VrstelKode { get; set; }
        public string VraestelKode { get; set; }
        public Nullable<short> DatabasisNommer { get; set; }
        public Nullable<int> GetalKandidateSubstelsel_A { get; set; }
        public Nullable<int> GetalKandidateSubstelsel_B { get; set; }
        public Nullable<short> GetalVraeOpVraestel { get; set; }
        public Nullable<short> MaksVraeBeantwoord { get; set; }
        public Nullable<int> VraestelMaksimum { get; set; }
        public Nullable<int> PuntestaatlMaksimum { get; set; }
        public string VraagNaam1 { get; set; }
        public Nullable<float> VraagMaks1 { get; set; }
        public Nullable<bool> TelVirVraestelMaks1 { get; set; }
        public string VraagNaam2 { get; set; }
        public Nullable<float> VraagMaks2 { get; set; }
        public Nullable<bool> TelVirVraestelMaks2 { get; set; }
        public string VraagNaam3 { get; set; }
        public Nullable<float> VraagMaks3 { get; set; }
        public Nullable<bool> TelVirVraestelMaks3 { get; set; }
        public string VraagNaam4 { get; set; }
        public Nullable<float> VraagMaks4 { get; set; }
        public Nullable<bool> TelVirVraestelMaks4 { get; set; }
        public string VraagNaam5 { get; set; }
        public Nullable<float> VraagMaks5 { get; set; }
        public Nullable<bool> TelVirVraestelMaks5 { get; set; }
        public string VraagNaam6 { get; set; }
        public Nullable<float> VraagMaks6 { get; set; }
        public Nullable<bool> TelVirVraestelMaks6 { get; set; }
        public string VraagNaam7 { get; set; }
        public Nullable<float> VraagMaks7 { get; set; }
        public Nullable<bool> TelVirVraestelMaks7 { get; set; }
        public string VraagNaam8 { get; set; }
        public Nullable<float> VraagMaks8 { get; set; }
        public Nullable<bool> TelVirVraestelMaks8 { get; set; }
        public string VraagNaam9 { get; set; }
        public Nullable<float> VraagMaks9 { get; set; }
        public Nullable<bool> TelVirVraestelMaks9 { get; set; }
        public string VraagNaam10 { get; set; }
        public Nullable<float> VraagMaks10 { get; set; }
        public Nullable<bool> TelVirVraestelMaks10 { get; set; }
        public string VraagNaam11 { get; set; }
        public Nullable<float> VraagMaks11 { get; set; }
        public Nullable<bool> TelVirVraestelMaks11 { get; set; }
        public string VraagNaam12 { get; set; }
        public Nullable<float> VraagMaks12 { get; set; }
        public Nullable<bool> TelVirVraestelMaks12 { get; set; }
        public string VraagNaam13 { get; set; }
        public Nullable<float> VraagMaks13 { get; set; }
        public Nullable<bool> TelVirVraestelMaks13 { get; set; }
        public string VraagNaam14 { get; set; }
        public Nullable<float> VraagMaks14 { get; set; }
        public Nullable<bool> TelVirVraestelMaks14 { get; set; }
        public string VraagNaam15 { get; set; }
        public Nullable<float> VraagMaks15 { get; set; }
        public Nullable<bool> TelVirVraestelMaks15 { get; set; }
        public string VraagNaam16 { get; set; }
        public Nullable<float> VraagMaks16 { get; set; }
        public Nullable<bool> TelVirVraestelMaks16 { get; set; }
        public string VraagNaam17 { get; set; }
        public Nullable<float> VraagMaks17 { get; set; }
        public Nullable<bool> TelVirVraestelMaks17 { get; set; }
        public string VraagNaam18 { get; set; }
        public Nullable<float> VraagMaks18 { get; set; }
        public Nullable<bool> TelVirVraestelMaks18 { get; set; }
        public string VraagNaam19 { get; set; }
        public Nullable<float> VraagMaks19 { get; set; }
        public Nullable<bool> TelVirVraestelMaks19 { get; set; }
        public string VraagNaam20 { get; set; }
        public Nullable<float> VraagMaks20 { get; set; }
        public Nullable<bool> TelVirVraestelMaks20 { get; set; }
        public string VraagNaam21 { get; set; }
        public Nullable<float> VraagMaks21 { get; set; }
        public Nullable<bool> TelVirVraestelMaks21 { get; set; }
        public string VraagNaam22 { get; set; }
        public Nullable<float> VraagMaks22 { get; set; }
        public Nullable<bool> TelVirVraestelMaks22 { get; set; }
        public string VraagNaam23 { get; set; }
        public Nullable<float> VraagMaks23 { get; set; }
        public Nullable<bool> TelVirVraestelMaks23 { get; set; }
        public string VraagNaam24 { get; set; }
        public Nullable<float> VraagMaks24 { get; set; }
        public Nullable<bool> TelVirVraestelMaks24 { get; set; }
        public string VraagNaam25 { get; set; }
        public Nullable<float> VraagMaks25 { get; set; }
        public Nullable<bool> TelVirVraestelMaks25 { get; set; }
        public string VraagNaam26 { get; set; }
        public Nullable<float> VraagMaks26 { get; set; }
        public Nullable<bool> TelVirVraestelMaks26 { get; set; }
        public string VraagNaam27 { get; set; }
        public Nullable<float> VraagMaks27 { get; set; }
        public Nullable<bool> TelVirVraestelMaks27 { get; set; }
        public string VraagNaam28 { get; set; }
        public Nullable<float> VraagMaks28 { get; set; }
        public Nullable<bool> TelVirVraestelMaks28 { get; set; }
        public string VraagNaam29 { get; set; }
        public Nullable<float> VraagMaks29 { get; set; }
        public Nullable<bool> TelVirVraestelMaks29 { get; set; }
        public string VraagNaam30 { get; set; }
        public Nullable<float> VraagMaks30 { get; set; }
        public Nullable<bool> TelVirVraestelMaks30 { get; set; }
        public Nullable<short> GetalKombinasiesVanKeuseVrae { get; set; }
        public Nullable<short> GetalKombinasiesTeBeantwoord { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo1 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo1 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae1 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo2 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo2 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae2 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo3 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo3 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae3 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo4 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo4 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae4 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo5 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo5 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae5 { get; set; }
        public Nullable<short> KeuseVraeEersteVrgNo6 { get; set; }
        public Nullable<short> KeuseVraeLaasteVrgNo6 { get; set; }
        public Nullable<short> KeuseVraeGetalVrae6 { get; set; }
        public Nullable<short> GetalAfdelingsGeheelKeuses { get; set; }
        public Nullable<short> GetalAfdelingsTeBeantwoord { get; set; }
        public Nullable<short> AfdelingEersteVrgNo1 { get; set; }
        public Nullable<short> AfdelingLaasteVrgNo1 { get; set; }
        public Nullable<short> AfdelingEersteVrgNo2 { get; set; }
        public Nullable<short> AfdelingLaasteVrgNo2 { get; set; }
        public Nullable<short> AfdelingEersteVrgNo3 { get; set; }
        public Nullable<short> AfdelingLaasteVrgNo3 { get; set; }
        public Nullable<short> AfdelingEersteVrgNo4 { get; set; }
        public Nullable<short> AfdelingLaasteVrgNo4 { get; set; }
        public Nullable<short> AfdelingEersteVrgNo5 { get; set; }
        public Nullable<short> AfdelingLaasteVrgNo5 { get; set; }
        public Nullable<short> AfdelingEersteVrgNo6 { get; set; }
        public Nullable<short> AfdelingLaasteVrgNo6 { get; set; }
        public Nullable<bool> WPM { get; set; }
        public Nullable<short> WPM_Min { get; set; }
        public Nullable<short> WPM_Max { get; set; }
        public Nullable<short> Foutvlag { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
