//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraestelLokale
    {
        public string VraestelKode { get; set; }
        public string Vakkode { get; set; }
        public int Vraestelno { get; set; }
        public string Lokaal { get; set; }
        public string Gebou { get; set; }
        public string Vraestelnaam { get; set; }
        public Nullable<int> Eetsaal { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
