//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vraestelle
    {
        public Nullable<bool> ValidTable { get; set; }
        public string VraestelK { get; set; }
        public string PaperCode { get; set; }
        public Nullable<short> PackSize { get; set; }
        public string PackSizes { get; set; }
        public string Vakkode { get; set; }
        public int Vrst { get; set; }
        public string VraestelNM { get; set; }
        public string VraestelNaam { get; set; }
        public Nullable<bool> Aangebied { get; set; }
        public Nullable<bool> NasionaleVraestelJaNee { get; set; }
        public Nullable<bool> VraestelUitstaande { get; set; }
        public string Nov1 { get; set; }
        public string Mrt1 { get; set; }
        public string Nov2 { get; set; }
        public string Mrt2 { get; set; }
        public string Nov3 { get; set; }
        public string Mrt3 { get; set; }
        public Nullable<bool> Druk1 { get; set; }
        public Nullable<int> VraestelMaksimumPunt { get; set; }
        public Nullable<short> GetalVrae { get; set; }
        public Nullable<int> VraestelNommer { get; set; }
        public string Sinapskode { get; set; }
        public Nullable<short> DrukVersion { get; set; }
        public Nullable<short> DrukVersion2 { get; set; }
        public Nullable<short> TipeAfronding { get; set; }
        public Nullable<bool> BuiteVraestel { get; set; }
        public string EksamenDatum { get; set; }
        public string Tyd { get; set; }
        public Nullable<short> Sessienommer { get; set; }
        public string BeginTyd { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<short> Besending { get; set; }
        public Nullable<int> Getalkandidate { get; set; }
        public Nullable<bool> OddPack { get; set; }
        public Nullable<bool> PakVan3 { get; set; }
        public Nullable<bool> PakVan5 { get; set; }
        public Nullable<bool> PakVan10 { get; set; }
        public Nullable<bool> PakVan15 { get; set; }
        public Nullable<bool> PakVan20 { get; set; }
        public Nullable<short> TotaalExtra { get; set; }
        public Nullable<short> Getal_CDs { get; set; }
        public Nullable<bool> Container { get; set; }
        public Nullable<bool> AnswerBook { get; set; }
        public Nullable<bool> VariablePackSize { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
