//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class VraestellePerKampu
    {
        public string Campus { get; set; }
        public string Vakkode { get; set; }
        public Nullable<int> Vrst { get; set; }
        public string SubjP { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
